In [1]:
import pandas as pd
import numpy as np

Part 1:

In [2]:
students = pd.read_csv("/workspaces/STA556/data/students.csv")
enrollments = pd.read_csv("/workspaces/STA556/data/enrollments.csv")
courses = pd.read_csv("/workspaces/STA556/data/courses.csv")

In [3]:
print(students.shape)
print(students.columns)
print(students.dtypes)
print(students.isnull().sum())

(30, 11)
Index(['student_id', 'first_name', 'last_name', 'program', 'year', 'age',
       'active', 'entry_term', 'gpa', 'credits_completed', 'advisor'],
      dtype='str')
student_id               str
first_name               str
last_name                str
program                  str
year                     str
age                  float64
active                   str
entry_term               str
gpa                  float64
credits_completed      int64
advisor                  str
dtype: object
student_id           0
first_name           0
last_name            0
program              0
year                 0
age                  2
active               0
entry_term           0
gpa                  3
credits_completed    0
advisor              1
dtype: int64

In [4]:
print(enrollments.shape)
print(enrollments.columns)
print(enrollments.dtypes)
print(enrollments.isnull().sum())

(59, 9)
Index(['enrollment_id', 'student_id', 'course_id', 'term', 'status',
       'midterm_score', 'final_score', 'project_score', 'attendance_pct'],
      dtype='str')
enrollment_id         str
student_id            str
course_id             str
term                  str
status                str
midterm_score       int64
final_score       float64
project_score     float64
attendance_pct    float64
dtype: object
enrollment_id     0
student_id        0
course_id         0
term              0
status            0
midterm_score     0
final_score       5
project_score     3
attendance_pct    2
dtype: int64

In [5]:
print(courses.shape)
print(courses.columns)
print(courses.dtypes)
print(courses.isnull().sum())

(8, 7)
Index(['course_id', 'department', 'course_number', 'course_title', 'credits',
       'level', 'delivery'],
      dtype='str')
course_id          str
department         str
course_number    int64
course_title       str
credits          int64
level              str
delivery           str
dtype: object
course_id        0
department       0
course_number    0
course_title     0
credits          0
level            0
delivery         0
dtype: int64

The Key columns are going to be student_id, course_id, and enrollment_id. These will allow us to merge the tables and find some further information out about the data.

The largest immediate concerns about the data quality stem from the amount of null entries and the sizes of the dataframes. Within the students dataframe age has 2 null entries, gpa has 3 null entries, and advisor has 1 null entry. In enrollments, final_score has 5 null entries, project_score has 3 null entries, and attendance_pct has 2 null entries. In courses there are no null entries. Another concern is that the sizes of each data set are drastically different, with students having 30 entries, enrollements 59, and courses 8. This means when we take a deeper look at the data we might run into some issues with duplicates.

Part 2

In [6]:
#1
students.loc[
    (students["program"] == "Mathematics") &
    (students["year"] == "1st")

]

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno
2,S1003,Noah,Garcia,Mathematics,1st,18.0,Yes,Spring 2024,2.81,18,Dr. Reed
13,S1014,Henry,Anderson,Mathematics,1st,20.0,Yes,Spring 2025,2.66,45,Dr. Shah
19,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108,Dr. Shah
27,S1028,Caleb,Hill,Mathematics,1st,20.0,No,Spring 2026,3.79,108,Dr. Reed

In [7]:
#2
students["high_gpa"] = students["gpa"] >= 3.5

High_math_gpa = students.loc[
    (students["program"] == "Mathematics") &
    (students["high_gpa"]),
    ["first_name", "last_name"]]
High_math_gpa

   first_name last_name
0       Avery    Nguyen
19     Daniel     Young
27      Caleb      Hill

In [8]:
#4
high_gpa_list = [gpa >= 3.5 for gpa in students["gpa"]]
sum(high_gpa_list)

10

In [9]:
#3
high_gpa_students = students.loc[
    students["gpa"] >= 3.5,
    ["first_name", "last_name"]
]
high_gpa_students

   first_name last_name
0       Avery    Nguyen
5        Liam  Martinez
6      Olivia     Brown
14        Mia    Thomas
17     Samuel      Hall
19     Daniel     Young
20      Layla      King
23       Owen     Green
24      Chloe     Baker
27      Caleb      Hill

Part 3

In [15]:
#I want to get student and enrollment merged on student_id
student_enrollment = pd.merge(
    students,
    enrollments,
    on = "student_id",
    how = "left",
    validate = "many_to_many",
    indicator = "True"
)[["student_id","first_name","last_name","enrollment_id","course_id","final_score","True"]]

In [14]:

course_final_grades = pd.merge(
    student_enrollment,
    courses,
    on = "course_id",
    how = "left",
    validate = "many_to_many",
)
course_final_grades[(course_final_grades["course_title"] == "Applied Statistics")]
#course_final_grades[["student_id","first_name","last_name","final_score","course_title","True"]]

,student_id,first_name,last_name,enrollment_id,course_id,final_score,True,department,course_number,course_title,credits,level,delivery
0,S1001,Avery,Nguyen,E5001,C102,65.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
5,S1003,Noah,Garcia,E5006,C102,76.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
16,S1008,Lucas,Wilson,E5017,C102,65.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
21,S1010,Mateo,Davis,E5021,C102,97.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
27,S1014,Henry,Anderson,E5027,C102,62.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
32,S1016,Leo,Moore,E5032,C102,89.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
33,S1017,Nora,Lewis,E5033,C102,97.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
41,S1020,Daniel,Young,E5041,C102,56.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
45,S1022,Julian,Wright,E5045,C102,61.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
46,S1023,Grace,Scott,E5046,C102,84.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
50,S1025,Chloe,Baker,E5050,C102,79.0,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid