In [3]:
import pandas as pd
import numpy as np

Part 1:

In [4]:
students = pd.read_csv("/workspaces/STA556/data/students.csv")
enrollments = pd.read_csv("/workspaces/STA556/data/enrollments.csv")
courses = pd.read_csv("/workspaces/STA556/data/courses.csv")

In [5]:
print(students.shape)
print(students.columns)
print(students.dtypes)
print(students.isnull().sum())

(30, 11)
Index(['student_id', 'first_name', 'last_name', 'program', 'year', 'age',
       'active', 'entry_term', 'gpa', 'credits_completed', 'advisor'],
      dtype='str')
student_id               str
first_name               str
last_name                str
program                  str
year                     str
age                  float64
active                   str
entry_term               str
gpa                  float64
credits_completed      int64
advisor                  str
dtype: object
student_id           0
first_name           0
last_name            0
program              0
year                 0
age                  2
active               0
entry_term           0
gpa                  3
credits_completed    0
advisor              1
dtype: int64

In [6]:
print(enrollments.shape)
print(enrollments.columns)
print(enrollments.dtypes)
print(enrollments.isnull().sum())

(59, 9)
Index(['enrollment_id', 'student_id', 'course_id', 'term', 'status',
       'midterm_score', 'final_score', 'project_score', 'attendance_pct'],
      dtype='str')
enrollment_id         str
student_id            str
course_id             str
term                  str
status                str
midterm_score       int64
final_score       float64
project_score     float64
attendance_pct    float64
dtype: object
enrollment_id     0
student_id        0
course_id         0
term              0
status            0
midterm_score     0
final_score       5
project_score     3
attendance_pct    2
dtype: int64

In [7]:
print(courses.shape)
print(courses.columns)
print(courses.dtypes)
print(courses.isnull().sum())

(8, 7)
Index(['course_id', 'department', 'course_number', 'course_title', 'credits',
       'level', 'delivery'],
      dtype='str')
course_id          str
department         str
course_number    int64
course_title       str
credits          int64
level              str
delivery           str
dtype: object
course_id        0
department       0
course_number    0
course_title     0
credits          0
level            0
delivery         0
dtype: int64

The Key columns are going to be student_id, course_id, and enrollment_id. These will allow us to merge the tables and find some further information out about the data.

The largest immediate concerns about the data quality stem from the amount of null entries and the sizes of the dataframes. Within the students dataframe age has 2 null entries, gpa has 3 null entries, and advisor has 1 null entry. In enrollments, final_score has 5 null entries, project_score has 3 null entries, and attendance_pct has 2 null entries. In courses there are no null entries. Another concern is that the sizes of each data set are drastically different, with students having 30 entries, enrollements 59, and courses 8. This means when we take a deeper look at the data we might run into some issues with duplicates.

Part 2

In [8]:
#1
students.loc[
    (students["program"] == "Mathematics") &
    (students["year"] == "1st")

]

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno
2,S1003,Noah,Garcia,Mathematics,1st,18.0,Yes,Spring 2024,2.81,18,Dr. Reed
13,S1014,Henry,Anderson,Mathematics,1st,20.0,Yes,Spring 2025,2.66,45,Dr. Shah
19,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108,Dr. Shah
27,S1028,Caleb,Hill,Mathematics,1st,20.0,No,Spring 2026,3.79,108,Dr. Reed

I wanted to find all students who were in their first year of the Mathematics program.

In [9]:
#2
students["high_gpa"] = students["gpa"] >= 3.5

High_math_gpa = students.loc[
    (students["program"] == "Mathematics") &
    (students["high_gpa"]),
    ["first_name", "last_name"]]
High_math_gpa

   first_name last_name
0       Avery    Nguyen
19     Daniel     Young
27      Caleb      Hill

I also wanted to find which Mathematics students had a "high" gpa (>3.5). I created a derived variable for those high gpa's, and then used that to filter students for those in Mathematics and those who had a high gpa.

In [10]:
#3 
high_gpa_students = students.loc[
    students["gpa"] >= 3.5,
    ["first_name", "last_name","program"]
]
high_gpa_students

   first_name last_name           program
0       Avery    Nguyen       Mathematics
5        Liam  Martinez        Statistics
6      Olivia     Brown        Statistics
14        Mia    Thomas        Statistics
17     Samuel      Hall  Computer Science
19     Daniel     Young       Mathematics
20      Layla      King  Computer Science
23       Owen     Green      Data Science
24      Chloe     Baker      Data Science
27      Caleb      Hill       Mathematics

I could also use .loc to find all students with a high gpa.

In [11]:

#4
high_gpa_list = [gpa >= 3.5 for gpa in students["gpa"]]
sum(high_gpa_list)

10

I just wanted to see how many students overall had a high gpa, and so I used list comphrehension to list all students by a True/False for whether they had a high gpa or not. I then summed those to find the total number of True entries.

Part 3

In [17]:
#I want to get student and enrollment merged on student_id. There 
student_enrollment = pd.merge(
    students,
    enrollments,
    on = "student_id",
    how = "left",
    validate = "1:m",
    indicator = "True"
)
student_enrollment[["student_id","first_name","last_name","term","enrollment_id","course_id","final_score","True"]]

,student_id,first_name,last_name,term,enrollment_id,course_id,final_score,True
0,S1001,Avery,Nguyen,Spring 2026,E5001,C102,65.0,both
1,S1001,Avery,Nguyen,Spring 2026,E5002,C106,80.0,both
2,S1001,Avery,Nguyen,Spring 2026,E5003,C103,67.0,both
3,S1002,Maya,Patel,Fall 2025,E5004,C106,NaN,both
4,S1002,Maya,Patel,Fall 2025,E5005,C101,55.0,both
5,S1003,Noah,Garcia,Fall 2026,E5006,C102,76.0,both
6,S1004,Sofia,Johnson,Spring 2026,E5007,C105,73.0,both
7,S1004,Sofia,Johnson,Fall 2025,E5008,C101,58.0,both
8,S1004,Sofia,Johnson,Fall 2026,E5009,C104,79.0,both
9,S1005,Ethan,Kim,Spring 2026,E5010,C101,57.0,both
10,S1005,Ethan,Kim,Fall 2025,E5011,C108,55.0,both
11,S1006,Liam,Martinez,Fall 2026,E5012,C105,NaN,both
12,S1006,Liam,Martinez,Fall 2026,E5013,C101,81.0,both
13,S1007,Olivia,Brown,Fall 2025,E5014,C103,93.0,both
14,S1007,Olivia,Brown,Spring 2026,E5015,C106,82.0,both
15,S1008,Lucas,Wilson,Spring 2026,E5016,C104,83.0,both
16,S1008,Lucas,Wilson,Fall 2025,E5017,C102,65.0,both
17,S1008,Lucas,Wilson,Spring 2026,E5018,C101,70.0,both
18,S1008,Lucas,Wilson,Fall 2026,E5059,C999,82.0,both
19,S1009,Emma,Chen,Fall 2026,E5019,C103,61.0,both
20,S1009,Emma,Chen,Spring 2026,E5020,C108,NaN,both
21,S1010,Mateo,Davis,Fall 2026,E5021,C102,97.0,both
22,S1010,Mateo,Davis,Fall 2026,E5022,C108,70.0,both
23,S1011,Isabella,Lopez,Fall 2026,E5023,C108,59.0,both
24,S1012,Elijah,Clark,Fall 2026,E5024,C108,76.0,both
25,S1013,Amara,Taylor,Fall 2025,E5025,C108,70.0,both
26,S1013,Amara,Taylor,Fall 2026,E5026,C104,78.0,both
27,S1014,Henry,Anderson,Fall 2025,E5027,C102,62.0,both
28,S1014,Henry,Anderson,Fall 2025,E5028,C101,NaN,both
29,S1015,Mia,Thomas,Fall 2026,E5029,C105,96.0,both
30,S1016,Leo,Moore,Fall 2026,E5030,C106,98.0,both
31,S1016,Leo,Moore,Fall 2025,E5031,C101,64.0,both
32,S1016,Leo,Moore,Spring 2026,E5032,C102,89.0,both
33,S1017,Nora,Lewis,Fall 2025,E5033,C102,97.0,both
34,S1017,Nora,Lewis,Spring 2026,E5034,C107,70.0,both
35,S1018,Samuel,Hall,Fall 2026,E5035,C108,87.0,both
36,S1018,Samuel,Hall,Fall 2026,E5036,C107,64.0,both
37,S1018,Samuel,Hall,Spring 2026,E5037,C105,NaN,both
38,S1019,Zoe,Allen,Fall 2025,E5038,C104,62.0,both
39,S1019,Zoe,Allen,Fall 2026,E5039,C103,77.0,both
40,S1020,Daniel,Young,Fall 2025,E5040,C103,61.0,both
41,S1020,Daniel,Young,Spring 2026,E5041,C102,56.0,both
42,S1021,Layla,King,Fall 2025,E5042,C107,68.0,both
43,S1021,Layla,King,Fall 2026,E5043,C101,92.0,both
44,S1022,Julian,Wright,Fall 2025,E5044,C107,74.0,both
45,S1022,Julian,Wright,Spring 2026,E5045,C102,61.0,both
46,S1023,Grace,Scott,Fall 2025,E5046,C102,84.0,both
47,S1023,Grace,Scott,Spring 2026,E5047,C106,74.0,both
48,S1024,Owen,Green,Fall 2026,E5048,C106,85.0,both
49,S1024,Owen,Green,Spring 2026,E5049,C101,84.0,both
50,S1025,Chloe,Baker,Fall 2025,E5050,C102,79.0,both
51,S1025,Chloe,Baker,Fall 2025,E5051,C106,58.0,both
52,S1026,Isaac,Adams,Fall 2026,E5052,C104,63.0,both
53,S1027,Elena,Nelson,Fall 2026,E5053,C107,64.0,both
54,S1028,Caleb,Hill,Fall 2025,E5054,C107,98.0,both
55,S1028,Caleb,Hill,Spring 2026,E5055,C105,95.0,both
56,S1029,Aria,Campbell,Spring 2026,E5056,C104,57.0,both
57,S1029,Aria,Campbell,Fall 2026,E5057,C108,62.0,both
58,S1030,Miles,Mitchell,NaN,NaN,NaN,NaN,left_only

There is alot of duplicates of students in here. This makes sense as each student can be taking multiple courses.

In [18]:

student_enrollment_courses = pd.merge(
    student_enrollment,
    courses,
    on = "course_id",
    how = "left",
    validate = "m:1",
)
student_enrollment_courses[(student_enrollment_courses["course_title"] == "Applied Statistics")]
#course_final_grades[["student_id","first_name","last_name","final_score","course_title","True"]]

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,...,final_score,project_score,attendance_pct,True,department,course_number,course_title,credits,level,delivery
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,...,65.0,65.0,94.7,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
5,S1003,Noah,Garcia,Mathematics,1st,18.0,Yes,Spring 2024,2.81,18,...,76.0,95.0,88.4,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
16,S1008,Lucas,Wilson,Data Science,4th,27.0,Yes,Spring 2024,2.89,45,...,65.0,79.0,NaN,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
21,S1010,Mateo,Davis,Data Science,4th,27.0,Yes,Fall 2023,2.59,24,...,97.0,81.0,79.5,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
27,S1014,Henry,Anderson,Mathematics,1st,20.0,Yes,Spring 2025,2.66,45,...,62.0,61.0,82.3,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
32,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96,...,89.0,75.0,74.4,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
33,S1017,Nora,Lewis,Mathematics,2nd,19.0,Yes,Spring 2025,2.88,96,...,97.0,87.0,96.9,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
41,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108,...,56.0,76.0,80.4,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
45,S1022,Julian,Wright,Statistics,3rd,19.0,Yes,Spring 2025,NaN,18,...,61.0,71.0,85.2,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
46,S1023,Grace,Scott,Data Science,1st,19.0,Yes,Fall 2023,2.49,45,...,84.0,86.0,80.6,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid
50,S1025,Chloe,Baker,Data Science,4th,19.0,Yes,Spring 2024,3.85,84,...,79.0,64.0,79.7,both,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid

Part 4

In [14]:
student_enrollment_courses.isna().sum()

student_id       0
first_name       0
last_name        0
term             1
enrollment_id    1
course_id        1
final_score      6
True             0
department       2
course_number    2
course_title     2
credits          2
level            2
delivery         2
dtype: int64

In [15]:
student_enrollment_courses.isna().mean()*100

student_id        0.000000
first_name        0.000000
last_name         0.000000
term              1.694915
enrollment_id     1.694915
course_id         1.694915
final_score      10.169492
True              0.000000
department        3.389831
course_number     3.389831
course_title      3.389831
credits           3.389831
level             3.389831
delivery          3.389831
dtype: float64

In [16]:
student_avg_score = student_enrollment.pivot_table(
    index = "student_id",
    columns = "term",
    values = "final_score",
    aggfunc= "mean"
)
student_avg_score

term        Fall 2025  Fall 2026  Spring 2026
student_id
S1001             NaN        NaN    70.666667
S1002            55.0        NaN          NaN
S1003             NaN       76.0          NaN
S1004            58.0       79.0    73.000000
S1005            55.0        NaN    57.000000
S1006             NaN       81.0          NaN
S1007            93.0        NaN    82.000000
S1008            65.0       82.0    76.500000
S1009             NaN       61.0          NaN
S1010             NaN       83.5          NaN
S1011             NaN       59.0          NaN
S1012             NaN       76.0          NaN
S1013            70.0       78.0          NaN
S1014            62.0        NaN          NaN
S1015             NaN       96.0          NaN
S1016            64.0       98.0    89.000000
S1017            97.0        NaN    70.000000
S1018             NaN       75.5          NaN
S1019            62.0       77.0          NaN
S1020            61.0        NaN    56.000000
S1021            68.0       92.0          NaN
S1022            74.0        NaN    61.000000
S1023            84.0        NaN    74.000000
S1024             NaN       85.0    84.000000
S1025            68.5        NaN          NaN
S1026             NaN       63.0          NaN
S1027             NaN       64.0          NaN
S1028            98.0        NaN    95.000000
S1029             NaN       62.0    57.000000

Replacing all the NaN values with 0 is a terrible idea, as a value of NaN in this case simply means they did not take any courses for that term. Replacing them with 0's would imply they had an average final score of 0, which is not the case.